server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_student?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    hibernate:
      generate_statistics: true
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        generate_statistics: true
        format_sql: true

  cloud:
    function:
      definition: reduceMachineProductMap
    stream:
      kafka:
        binder:
#          default: localhost
#            ex: - localhost:9091
#                - localhost:9092
          brokers: localhost
#          default: 9092
          defaultBrokerPort: 9092
      bindings:
        reduceMachineProductMap-in-0:
#          topic send message from producer
          destination: initialTopic
        reduceMachineProductMap-out-0:
#          topic send message from consumer
          destination: topicReturn
#        changeMachineStatus-in-0:
#          destination: machineNetworkConnectionChange
  jackson:
#    config hidden object null
    default-property-inclusion: non_absent