server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_student?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    hibernate:
      generate_statistics: true
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        generate_statistics: true
        format_sql: true
  jackson:
#    config hidden object null
    default-property-inclusion: non_absent